Add Databases

diff --git a/.github/workflows/PR.yaml b/.github/workflows/PR.yaml
--- a/.github/workflows/PR.yaml
+++ b/.github/workflows/PR.yaml
@@ -13,3 +13,12 @@ jobs:
       - name: desitination branch name
         run: |
           echo ${GITHUB_BASE_REF}
+      - name: Hash commit
+        run: |
+          echo ${GITHUB_SHA}
+      - name: Check if Hash commit in develop branch
+        run: |
+          if [ 0 -eq ${git branch --contains $GITHUB_SHA|grep -c origin/develop} ];
+             then
+                 echo "${GITHUB_SHA} not found in origin/develop. Aborting script"
+                 exit 1
